[package]
edition = "2018"
name = "pkg_audit_exporter"
version = "0.1.0"
[dependencies]
log = "*"
pretty_env_logger = "0.4"
prometheus_exporter = "0.8"
rand = "*"
thiserror = "1"

[dev-dependencies]
pretty_assertions = "1"
