[package]
edition = "2018"
name = "pkg_audit_exporter"
version = "0.1.0"

[dependencies]
prometheus_exporter = "0.8"
thiserror = "1"
pretty_env_logger = "0.4"

[dev-dependencies]
pretty_assertions = "1"