[package]
edition = "2021"
name = "pkg_audit_exporter"
version = "0.1.0"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
prometheus_exporter = "0.8"
rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
itertools = "0.12.1"

[dev-dependencies]
pretty_assertions = "1"
